# Generated by Django 3.0.7 on 2020-06-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0004_auto_20200614_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='carousel_off',
            field=models.BooleanField(default=True),
        ),
    ]
