# Generated by Django 3.0.7 on 2020-06-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0005_photo_carousel_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('homepage_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_page_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=40, null=True)),
                ('carousel_off', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteLink',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='carousel_off',
        ),
    ]
