# Generated by Django 3.0.7 on 2020-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0006_auto_20200616_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.TextField(max_length=200)),
                ('link', models.TextField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('video_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['video_order'],
            },
        ),
        migrations.DeleteModel(
            name='NewsletterUser',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['photo_order']},
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
