# Generated by Django 3.0.7 on 2020-06-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0008_auto_20200621_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('info', models.TextField(blank=True, max_length=600)),
                ('info_2', models.TextField(blank=True, max_length=600)),
                ('event_info', models.TextField(blank=True, max_length=600)),
                ('event_image', models.ImageField(upload_to='camps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mediaPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media-carousel')),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('photo_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['photo_order'],
            },
        ),
    ]
