# Generated by Django 3.0.7 on 2020-07-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0010_auto_20200701_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='info_detail',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
