# Generated by Django 3.0.7 on 2020-07-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0011_camp_info_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='camp_page_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
