# Generated by Django 3.0.7 on 2020-07-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0012_siteconfiguration_camp_page_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='camp_page_title',
            new_name='camp_title',
        ),
    ]
