# Generated by Django 3.0.7 on 2020-07-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0014_camp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='camp_paypal',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
