# Generated by Django 3.0.7 on 2020-07-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0015_siteconfiguration_camp_paypal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='event_image',
            new_name='camp_image',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='detail_info',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='event_info',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='info',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='info_detail',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='camp_paypal',
        ),
        migrations.AddField(
            model_name='camp',
            name='camp_details',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='camp',
            name='list_info',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='camp',
            name='page_intro',
            field=models.TextField(blank=True, max_length=1200),
        ),
    ]
