# Generated by Django 3.0.7 on 2020-07-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0016_auto_20200728_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='camp_image',
        ),
        migrations.AddField(
            model_name='camp',
            name='image',
            field=models.ImageField(null=True, upload_to='camps'),
        ),
        migrations.AddField(
            model_name='camp',
            name='list_image',
            field=models.ImageField(null=True, upload_to='camps'),
        ),
    ]
