# Generated by Django 3.0.7 on 2020-07-28 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0017_auto_20200728_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='camp_details',
            new_name='details',
        ),
    ]
