# Generated by Django 3.0.7 on 2020-07-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0018_auto_20200728_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='paypal_link',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
