# Generated by Django 3.0.7 on 2020-07-28 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_app', '0022_auto_20200728_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='date_of_camp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='camp',
            name='sign_up_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
